feat: add sound play animation
Kaiyiwing/qwerty-learner pull request #125
Opened 2021-07-24 09:20 UTC by AEPKILL

1. 升级了 `use-sound` 版本，不会再抛 `Warning: Can't perform a React state update on an unmounted component.`
2. 添加了一个单词声音播放动画，点击或者使用 Ctrl + J 可以再播放一次单词声音 (有时候写到一半想再听一遍单词发音)
3. 移除了发音选项中的“关闭”，因为已经有一个关闭语言的选项了，这里显得有点多余
4. 使用 `use-sound` 重写了 `usePronunciation`，`use-sound` 底层使用了 `Howler` 可以兼容更多场景发音

2021-07-25 05:31 UTC, Kaiyiwing commented
非常感谢您贡献这些非常酷的 feature ！

这个 pr 可能不会非常快的合并，主要基于以下两个原因，希望您能理解
1. 我最近用来 review 的时间不太多，也欢迎社区中的人参与到 review 的工作中来。
2. 从后台来看，项目目前平均日活500左右，而在项目初期我们经历过未发现的潜在  bug 导致的问题，所以我会在该 pr 的预览环境测试一段时间后进行合并。 我们也在计划为项目引入自动化测试，欢迎社区中有测试经验的贡献者参与进来。

2021-07-29 06:32 UTC, Kaiyiwing commented
目前有两个问题
1. 发音选项中的“关闭”是有意义的，因为另一个开关声音的按钮是开关键盘音，而不是开关发音。这确实也有歧义。我的建议是保留“关闭”选项，也修改另一个开关声音按钮hover时的信息为“开关键盘声”
2. 是否应该找个合适的方式告知用户“ctrl/command + J”是再次朗读，例如hover带单词后的播放按钮就会显示“按ctrl/command + J再次朗读单词音”


以及有个设计相关的问题，单词后的 播放按钮是否美观，或许可以试试移到其他地方，例如单词的上一行并居中，或者 汉语意思的下一行并居中。 这个需要更多的意见～ @chengluyu @CLDXiang

2021-07-29 07:14 UTC, chengluyu commented
目前选项有点多。或许我们可以先解决这个 PR，然后做一个单独的设置面板，把打字时用不到的选项放进去。

2021-07-29 07:34 UTC, Kaiyiwing commented
> 目前选项有点多。或许我们可以先解决这个 PR，然后做一个单独的设置面板，把打字时用不到的选项放进去。

对于这个，我倾向于类似于 Mac 上 Bartender 的设计，在目前右上角设计的基础上，有一个更多的ICON，点击一下“滑”出所有的设置

2021-07-29 07:51 UTC, chengluyu requested changes

2021-07-29 07:51 UTC, chengluyu commented on src/store/AppState.tsx
> +export type PronunciationType = 'us' | 'uk'
根据 @Kaiyiwing 的意见，需要回退这里的代码。

2021-07-29 07:51 UTC, chengluyu commented on src/pages/Typing/hooks/usePronunciation.ts
> -        break
根据 @Kaiyiwing 的意见，需要回退这里的代码。

2021-07-29 07:51 UTC, chengluyu commented on src/pages/Typing/PronunciationSwitcher/index.tsx
> -          <option value="false">关闭</option>
根据 @Kaiyiwing 的意见，需要回退这里的代码。

2021-07-29 07:51 UTC, chengluyu commented on src/hooks/usePronunciation.ts
> +  return { play, stop, isPlaying }
根据 @Kaiyiwing 的意见，需要修改这里的返回值。

2021-07-29 07:51 UTC, chengluyu commented on src/components/SoundIcon/index.tsx
> +  )
可否找寻一下避免使用 `useImperativeHandle` 的方法？

2021-07-29 07:51 UTC, chengluyu commented on src/components/WordSound/index.tsx
> +const WordSound: React.FC<WordSoundProps> = React.memo(({ word, inputWord, ...rest }) => {
建议这里没必要用 `React.memo`。

2021-07-29 07:54 UTC, chengluyu requested changes
我根据 @Kaiyiwing 的意见审阅了代码。语音菜单里的「关闭」还需要保留。除了 `useImperativeHandle` 我觉得还有更好的方法外，没什么大问题。

😂以及这个 PR 信息量好大，下次提交 PR 的时候可以分开搞。

2021-07-29 08:42 UTC, CLDXiang commented
> 目前有两个问题
> 
> 1. 发音选项中的“关闭”是有意义的，因为另一个开关声音的按钮是开关键盘音，而不是开关发音。这确实也有歧义。我的建议是保留“关闭”选项，也修改另一个开关声音按钮hover时的信息为“开关键盘声”
> 2. 是否应该找个合适的方式告知用户“ctrl/command + J”是再次朗读，例如hover带单词后的播放按钮就会显示“按ctrl/command + J再次朗读单词音”
> 
> 以及有个设计相关的问题，单词后的 播放按钮是否美观，或许可以试试移到其他地方，例如单词的上一行并居中，或者 汉语意思的下一行并居中。 当然这只是我个人的意见，也需要更多人的看法～ @chengluyu @CLDXiang

我也认为播放按钮换个位置会好一些，考虑到鼠标的交互区主要在右上，是否放在中心区域也有讨论余地

2021-07-29 10:26 UTC, Kaiyiwing commented
确实
我也感觉对一个 pr 来说，功能有点太多了，以后可以尝试每一个细分功能一个 pr，对我们 review 和你自己梳理代码都比较友好。

2021-07-29 13:30 UTC, AEPKILL commented
各位的意见已收到，我周五下班再来改吧。

2021-07-30 12:22 UTC, AEPKILL commented
根据各位的意见:
1. 回退了单词发音设置
2. 移除了使用 `useImperativeHandle`
3. 增加了单词发音快捷键提升

关于发音动画摆放位置未修改，期待更好的 UI 设计

2021-07-31 10:08 UTC, AEPKILL commented on src/hooks/usePronunciation.ts
> +  return { play, stop, isPlaying }
这里我有点不理解『修改返回值』的意思

2021-07-31 10:39 UTC, AEPKILL commented on src/components/WordSound/index.tsx
> +const WordSound: React.FC<WordSoundProps> = React.memo(({ word, inputWord, ...rest }) => {
这是应用 `React.memo` 的性能分析
![屏幕截图 2021-07-31 182956](https://user-images.githubusercontent.com/9626630/127737113-113e32d8-0f14-467a-bce6-5424da5d4e55.png)
这是未应用 `React.memo` 时的性能分析
![image](https://user-images.githubusercontent.com/9626630/127737271-5a4c02d1-47b1-4b58-b374-e1977417b6a4.png)


可以看出在 `WordSound` 明显更消耗性了，事实上我建议更多的组件应用 `React.memo`，因为它只是简单的对比一下 `props` 是一个 `O(1)` 的算法，如果不使用的话在每次外部状态发生变化的时候，组件首先会经历创建创建 `VDom` 和 `VDom diff` 的过程，应用 `React.memo` 在绝大部分场景都可以提高性能。

2021-07-31 10:45 UTC, chengluyu commented on src/components/WordSound/index.tsx
> +const WordSound: React.FC<WordSoundProps> = React.memo(({ word, inputWord, ...rest }) => {
感谢。有理有据，令人信服。

2021-08-01 06:13 UTC, AEPKILL commented on src/hooks/usePronunciation.ts
> +  return { play, stop, isPlaying }
@chengluyu

2021-08-02 04:04 UTC, Kaiyiwing commented
![image](https://user-images.githubusercontent.com/44634134/127802835-81a4a388-4b70-4692-aa8c-bb4fc9fa9755.png)

当 Hover 单词上的 喇叭Icon 时，应该显示"ctrl + J 再次朗读发音"

2021-08-02 05:25 UTC, Kaiyiwing approved these changes
我个人感觉代码没有问题，我在 preview 的构建上测试了几个章节也没遇到 bug。非常感谢贡献，我也从您的代码中学到了很多。

对于 喇叭Icon 的位置，我会本地试验一下其他的设计方案

2021-08-02 05:25 UTC, Kaiyiwing commented on src/hooks/usePronunciation.ts
> +  return { play, stop, isPlaying }
我觉得这里应该没有需要修改的

2021-08-04 03:28 UTC, merged