feat: speak trans by web speech api
Kaiyiwing/qwerty-learner pull request #409
Opened 2023-04-18 10:10 UTC by OBQun

Fixes #314, Links #285 

**Browser compatibility:**

[Web Speech API - SpeechSynthesis - Web APIs | MDN](https://developer.mozilla.org/zh-CN/docs/Web/API/Web_Speech_API#api.speechsynthesis)

2023-04-18 10:25 UTC, OBQun commented
有些遗留问题
1. 之前的单词发音来自Api请求的音频文件, 我没有找到合适的触发时机来实现首次进入读出单词后继续读出释义, 如果全部使用 `SpeechSynthesis` Api 可以做到, 因为有一个内置的全局的队列;
2. 要更好的使用该 Api 应指定所阅读文字的语言, 传入如 `lang: 'zh-CN'` 配置, 不然有可能把德文识别成英语读出. 如此需要变更数据结构新增 `lang` 字段来支持.

2023-04-26 23:04 UTC, chengluyu requested changes

2023-04-26 23:04 UTC, chengluyu commented on src/pages/Typing/components/CurrentWord/components/Translation/index.tsx
> +        />
Can you add a tooltip to the speaker icon? For example, 
![image](https://user-images.githubusercontent.com/2239547/234721023-a603459f-2f95-4c0b-b24b-e2225ec048b0.png)

2023-05-13 12:14 UTC, Kaiyiwing commented
🤔️ 是我浏览器版本的问题, 在 mac os 下，arc、Safari、chrome 均无法实现朗读？

2023-05-17 16:44 UTC, Kaiyiwing approved these changes

2023-05-17 16:45 UTC, merged