feat: new Gallery UI
Kaiyiwing/qwerty-learner pull request #414
Opened 2023-04-19 16:20 UTC by Kaiyiwing

![2691681890582_ pic](https://user-images.githubusercontent.com/44634134/233138177-05bdea16-e52a-43a6-90d5-6fcaa3132a39.jpg)
![2701681890582_ pic](https://user-images.githubusercontent.com/44634134/233138195-1f345fd3-6d79-4a01-a352-d2189dc8454c.jpg)

2023-04-23 15:31 UTC, zhuzhux commented on src/pages/Gallery-N/CategoryDicts.tsx
> +import { GalleryContext } from '.'
`import { GalleryContext } from './index'`, `./index`会明确一点

2023-04-23 15:31 UTC, zhuzhux commented on src/index.tsx
```
const ROOT = document.getElementById('root')
ROOT && createRoot(ROOT).render(<Root />)
```

2023-04-23 15:31 UTC, zhuzhux commented on src/pages/Gallery-N/DictionaryWithoutCover.tsx
> +  const DictStats = useDictStats(dictionary.id, isVisible)
DictStats 确认大小写

2023-04-23 15:31 UTC, zhuzhux commented on src/pages/Gallery-N/DictRequest.tsx
> +          onClose={() => onClosePanel()}
```
...
onClose={onClosePanel}
...
```

2023-04-23 15:31 UTC, zhuzhux commented on src/pages/Gallery-N/index.tsx
> +  const currentLanguageCategoryDicts = useMemo(
```
  const { groupedByCategoryAndTag } = useMemo(() => { 
    const currentLanguageCategoryDicts = dictionaries.filter((dict) => dict.languageCategory === galleryState.currentLanguageTab)
    const groupedByCategory = Object.entries(groupBy(currentLanguageCategoryDicts, (dict) => dict.category))
    const groupedByCategoryAndTag = groupedByCategory.map(([category, dicts]) => [category, groupByDictTags(dicts)])
    
    return {
      groupedByCategoryAndTag
    }

  },[galleryState.currentLanguageTab])
```
其实是同一个状态改变引起的

2023-04-23 16:52 UTC, Kaiyiwing commented
感谢 @zhuzhux review，相关问题已经修改 ❤️

2023-04-24 08:49 UTC, chengluyu requested changes

2023-04-24 08:49 UTC, chengluyu commented on src/pages/Gallery-N/DictRequest.tsx
> +      </span>
```suggestion
      <button className="cursor-pointer pr-6 text-sm text-indigo-500" onClick={onOpenPanel}>
        没有找到想要的词典？
      </button>
```

2023-04-24 08:49 UTC, chengluyu commented on src/pages/Gallery-N/hooks/useChapterStats.ts
> +  const totalWrongCount = records.reduce((total, { wrongCount }) => total + (wrongCount || 0), 0)
```suggestion
  const totalWrongCount = records.reduce((total, { wrongCount }) => total + (wrongCount ?? 0), 0)
```

2023-04-24 09:05 UTC, chengluyu approved these changes

2023-04-24 09:14 UTC, merged

2023-04-24 09:14 UTC, chengluyu commented on src/pages/Gallery-N/ChapterList/ChapterRow.tsx
> +import { useEffect, useRef } from 'react'
```suggestion
import { useEffect, useRef } from 'react' // hello
```