refactor: use unplugin-icons to unify all icons
Kaiyiwing/qwerty-learner pull request #439
Opened 2023-04-26 11:12 UTC by mancuoj

这是一个长期 PR：
我会在接下里的时间里逐步修改，请暂时不要合并

2023-04-26 16:04 UTC, Kaiyiwing commented
正在进行中的 pr 可以设置为 draft pr

2023-04-26 22:48 UTC, chengluyu requested changes
Hi. Thank you for your contribution! I found some problems. Please fix them.

2023-04-26 22:48 UTC, chengluyu commented on src/pages/Gallery-N/index.tsx
> +import TablerX from '~icons/tabler/x'
```suggestion
import IconX from '~icons/tabler/x'
```

2023-04-26 22:48 UTC, chengluyu commented on src/pages/Gallery-N/index.tsx
> +          <TablerX className="absolute right-20 top-10 mr-2 h-7 w-7 cursor-pointer text-gray-400" onClick={onBack} />
```suggestion
          <IconX className="absolute right-20 top-10 mr-2 h-7 w-7 cursor-pointer text-gray-400" onClick={onBack} />
```

2023-04-26 22:48 UTC, chengluyu commented on src/pages/Gallery-N/index.tsx
> +import TablerX from '~icons/tabler/x'
TablerX is a confusing name.

2023-04-26 22:48 UTC, chengluyu commented on src/pages/Gallery/ChapterButton.tsx
> +import HeroiconsCheckCircle from '~icons/heroicons/check-circle-solid'
```suggestion
import IconCheckCircle from '~icons/heroicons/check-circle-solid'
```

2023-04-26 22:48 UTC, chengluyu commented on src/pages/Gallery/ChapterButton.tsx
> +        <HeroiconsCheckCircle className="absolute -bottom-4 -right-4 h-18 w-18 text-6xl text-green-500 opacity-60 dark:text-green-300" />
```suggestion
        <IconCheckCircle className="absolute -bottom-4 -right-4 h-18 w-18 text-6xl text-green-500 opacity-60 dark:text-green-300" />
```

2023-04-26 22:48 UTC, chengluyu commented on src/pages/Gallery/ChapterButton.tsx
> +import HeroiconsCheckCircle from '~icons/heroicons/check-circle-solid'
Same, please don´t include library´s name in the component.

2023-04-26 22:48 UTC, chengluyu commented on vite.config.ts
> +              '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256"><path d="M289.44,256H477.67c17.93,0,33.86,15.57,34.33,33.48V477.72A35.09,35.09,0,0,1,477.66,512H289.5A35.14,35.14,0,0,1,25
Please load the SVG from files. For example,

```
  return {
    plugins: [
      react({ babel: { plugins: [jotaiDebugLabel, jotaiReactRefresh] } }),
      visualizer() as PluginOption,
      Icons({
        compiler: 'jsx',
        jsx: 'react',
        customCollections: {
          'my-icons': {
            xiaohongshu: await fs.readFile("xiaohongshu.svg", { encoding: "utf-8" }),
```

2023-04-26 22:48 UTC, chengluyu commented on src/pages/Typing/components/SoundSwitcher/index.tsx
> +import HeroiconsSpeakerWave from '~icons/heroicons/speaker-wave-solid'
```suggestion
import IconSpeakerWave from '~icons/heroicons/speaker-wave-solid'
```

2023-04-26 22:48 UTC, chengluyu commented on src/pages/Typing/components/SoundSwitcher/index.tsx
> +            <HeroiconsSpeakerWave className="icon" />
```suggestion
            <IconSpeakerWave className="icon" />
```

2023-04-26 22:48 UTC, chengluyu commented on src/pages/Typing/components/Switcher/index.tsx
> +import TablerRepeatOnce from '~icons/tabler/repeat-once'
Same here. Please do not include library's name in component names.

2023-04-26 22:48 UTC, chengluyu commented on src/pages/Typing/components/ShareButton/index.tsx
> +import TablerShare2 from '~icons/tabler/share-2'
Same here. Please do not include library's name in component names.

2023-04-26 22:48 UTC, chengluyu commented on src/pages/Typing/components/ShareButton/SharePicDialog.tsx
> +import HeroiconsXMark from '~icons/heroicons/x-mark-solid'
Same here. Please do not include library's name in component names.

2023-04-26 22:48 UTC, chengluyu commented on src/pages/Typing/components/Setting/index.tsx
> +import TablerX from '~icons/tabler/x'
Same here. Please do not include library's name in component names.

2023-04-26 22:48 UTC, chengluyu commented on src/components/Footer/index.tsx
> +import TwemojiFlagChina from '~icons/twemoji/flag-china'
Please do not include library's name in component names.

2023-04-26 22:48 UTC, chengluyu commented on src/pages/Gallery-N/DictRequest.tsx
> +import TablerBook2 from '~icons/tabler/book-2'
Same here. Please do not include the library's name in component names.

2023-04-27 16:21 UTC, Kaiyiwing commented
<img width="277" alt="CleanShot 2023-04-28 at 00 21 19@2x" src="https://user-images.githubusercontent.com/44634134/234927100-46a5b80c-b1cf-49a1-ae17-0fa4a35aa72d.png">

看起来这里 logo 分辨率有点低的样子，而且两侧被裁切掉了

2023-04-27 16:31 UTC, Kaiyiwing commented on src/components/Footer/index.tsx
> -        iconClassName="text-cyan-600 bg-cyan-300"
🤔️ 这个地方把所有 icon 的 bg 移除掉的目的是？

2023-04-27 16:31 UTC, Kaiyiwing commented on src/components/Footer/index.tsx
> +        {/* <button
这里为啥注释掉了

2023-04-27 16:32 UTC, mancuoj commented on src/components/Footer/index.tsx
> +        {/* <button
看起来跟咖啡图标的功能重合了（其实是忘了取消注释，你看是保留还是

2023-04-27 16:33 UTC, mancuoj commented on src/components/Footer/index.tsx
> -        iconClassName="text-cyan-600 bg-cyan-300"
这里是因为之前的圆形背景在暗黑模式下颜色看起来特别奇怪，上一个问题看起来要大改一下InfoPanel的样式

2023-04-27 16:38 UTC, Kaiyiwing commented on src/components/Footer/index.tsx
> +        {/* <button
还是保留吧

2023-04-28 04:29 UTC, Kaiyiwing approved these changes

2023-04-28 04:30 UTC, merged