Add a new page for viewing, selecting dictionaries and chapters
Kaiyiwing/qwerty-learner pull request #45
Opened 2021-02-06 19:18 UTC by chengluyu

2021-02-07 08:49 UTC, sdu-gyf requested changes
If the user clicks on the switch button after practicing a part of the word on the original page, and then clicks back to practice (without switching the dictionary) the user's original input data (word progress, input time, speed, correct number, correct rate and other data) disappears (the original page logic does not lead to this bug).Would you like to fix this bug?

2021-02-07 08:49 UTC, sdu-gyf commented on src/pages/Gallery/DictionaryCard.tsx
> +}
当选中名字比较长的章节的适合，button的大小会发生变化，比较影响观感体验，能不能在最开始处理的时候就加上 icon 的宽度 ?

2021-02-07 08:49 UTC, sdu-gyf commented on src/pages/Gallery/index.tsx
> +        </NavLink>
这样强行跳转回 "/" 路由会导致的问题是: 用户如果在原页面练习一部分单词之后，点击切换按钮，又点击返回练习(即不进行切换词典操作)用户原输入数据（单词进度，输入时间，速度，正确数，正确率等数据）消失（原页面逻辑不会导致这一点）。

2021-02-07 08:49 UTC, sdu-gyf commented on src/pages/Typing/index.tsx
> +            </NavLink>
感觉还是显示当前词典名称比较好？

2021-02-07 10:15 UTC, chengluyu commented on src/pages/Gallery/DictionaryCard.tsx
> +}
这里的 UI 还没有做完，我在想有没有更好的解决方案。

2021-02-07 10:16 UTC, chengluyu commented on src/pages/Gallery/DictionaryCard.tsx
> +}
我现在的打算是做一个可以移动的 focus outline，这个 outline 会高亮出当前的词典。同时还会有一个二级菜单显示当前的章节。

2021-02-07 10:17 UTC, chengluyu commented on src/pages/Gallery/index.tsx
> +        </NavLink>
这里是故意这么做的。

因为当前是在 `App` 把进度存储到 `localStorage` 中的，我的目标是在 `AppStateProvider` 中进行 persistent，所以这里的代码就不需要了，等做完进度在 `AppStateProvider` 的 persistent 这里只需要用一个类似 `useProgress` 的 hook 就可以访问进度了。

2021-02-07 10:18 UTC, chengluyu commented on src/pages/Typing/index.tsx
> +            </NavLink>
这里还没重构完，我正在重写整个 `DictSwitcher`。

2021-02-07 10:25 UTC, sdu-gyf commented on src/pages/Gallery/index.tsx
> +        </NavLink>
ok！

2021-02-09 10:20 UTC, sdu-gyf approved these changes

2021-02-09 12:14 UTC, sdu-gyf requested changes

2021-02-09 12:14 UTC, sdu-gyf commented on src/pages/Typing/index.tsx
> +      ) : (
现在切换完词典 会一直处于 Loading 状态

2021-02-09 12:14 UTC, sdu-gyf commented on src/pages/Typing/hooks/useWordList.ts
> +    return { words, totalChapters: Math.ceil(words.length / numWordsPerChapter) }
目前我在 线上预览的时候 会出现请求 json 文件成功(get 返回200 然后持续返回 304) 但是一直 loading ，此 http 请求预览为 You need to enable JavaScript to run this app. 返回的不是 json 字典 而是 html 文件

2021-02-09 12:18 UTC, sdu-gyf commented on src/pages/Typing/index.tsx
> +      ) : (
不是这里的问题

2021-02-09 14:24 UTC, chengluyu commented on src/pages/Typing/hooks/useWordList.ts
> +    return { words, totalChapters: Math.ceil(words.length / numWordsPerChapter) }
好，有些词典文件改名了，但我 rebase 的时候忘了修改。显示这行字是预览器的默认行为：Chrome 的预览器在预览 HTML 的时候，不会执行其中的 JavaScript，因此会显示 `<noscript><noscript/>` 标签中的内容。

2021-02-09 14:24 UTC, chengluyu commented on src/resources/dictionary.ts
> +console.log(dictionaries)
Of course.

2021-02-09 14:26 UTC, sdu-gyf commented on src/pages/Typing/hooks/useWordList.ts
> +    return { words, totalChapters: Math.ceil(words.length / numWordsPerChapter) }
got it

2021-02-09 14:34 UTC, sdu-gyf approved these changes

2021-02-09 16:35 UTC, merged